version: '3'

tasks:
  build:
    desc: "Build the container with name 'pim'"
    cmds:
      - docker build -t pim .

  run:
    desc: "Run the container 'pim'"
    cmds:
      - docker run -d --name pcon -p 9001:5432 pim

  rm:
    desc: "Stop and delete the container 'pim'"
    cmds:
      - docker stop pcon && docker rm pcon && docker image rm pim

  restart:
    desc: "Remove, rebuild and run container 'pim'"
    cmds:
      - go-task rm
      - go-task build
      - go-task run
