# Resolution

SCALING = 3.0
W = 320 * SCALING
H = 180 * SCALING

BLOCK_SIDE = H / 10
PLACEHOLDER_COLOR = (255, 0, 200)
PLACEHOLDER_COLOR_2 = (0, 255, 0)

PLAYER_HEIGHT = H / 6
PLAYER_WIDTH = W / 20

TOP_OFFSET_SPRITE = 5 * SCALING
LEFT_OFFSET_SPRITE = 10 / 3 * SCALING

PLAYER_SPEED = 0.5 / 3 * SCALING

# Refresh rate

FPS = 60.0
ANIMATION_FPS = 10

# Assets

GAME_TITLE = "Base Game"
ASSETS_PLAYER_PATH = "assets/player"
IDLE = "idle"
RUN = "run"
JUMP = "jump"
FALL = "fall"

# Movements

MAX_GRAVITY = 2
JUMP_FORCE = 1.8
GRAVITY_GROWTH = 0.1
