# Resolution

SCALING = 3.0
W = 320 * SCALING
H = 180 * SCALING

# Refresh rates

FPS = 60.0
ANIMATION_FPS = 10

# Assets

GAME_TITLE = "Base Game"
ASSETS_PLAYER_PATH = "assets/player"
IDLE = "idle"
RUN = "run"
JUMP = "jump"
FALL = "fall"
CROUCH = "crouch_test"

# Assets sizing

BLOCK_SIDE = H / 9

PLAYER_HEIGHT = BLOCK_SIDE * 2 - 10
PLAYER_WIDTH = W / 20

PLAYER_HEIGHT_CROUCH = PLAYER_HEIGHT * 2 / 3

TOP_OFFSET_SPRITE = 6 * SCALING
TOP_OFFSET_SPRITE_CROUCH = 12 * SCALING
LEFT_OFFSET_SPRITE = 10 / 3 * SCALING

PLAYER_SPRITE_WIDTH_SCALE = 3.5
PLAYER_SPRITE_HEIGHT_SCALE = 1.4

# Movements

MAX_GRAVITY = 2
JUMP_FORCE = 1.8
GRAVITY_GROWTH = 0.1
PLAYER_SPEED = 0.5 / 3 * SCALING

# Debug

PLACEHOLDER_COLOR = (255, 0, 200)
PLACEHOLDER_COLOR_2 = (0, 255, 0)
