[package]
name = "tmp-comptes"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
