version: '3'

tasks:
  build:
    desc: "Build the container with name 'pim'"
    cmds:
      - docker build -t pim docker/

  run:
    desc: "Run the container 'pim'"
    cmds:
      - docker run -d --name pcon -p 9001:5432 pim

  rm:
    desc: "Stop and delete the container 'pim'"
    cmds:
      - docker stop pcon && docker rm pcon && docker image rm pim

  restart:
    desc: "Remove, rebuild and run container 'pim'"
    cmds:
      - go-task rm
      - go-task build
      - go-task run

  goose-up:
    desc: "Run goose up"
    cmds:
      - go run main.go goose --action up

  goose-down:
    desc: "Run goose down"
    cmds:
      - go run main.go goose --action down

  goose-status:
    desc: "Run goose status"
    cmds:
      - go run main.go goose --action status
